sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sarangpadlakar/docker-react .

script:
  - docker run -e CI=true sarangpadlakar/docker-react npm run test -- --coverage